-- DROP SCHEMA ACCOUNTS CASCADE;

CREATE SCHEMA ACCOUNTS;

-- DROP TABLE ACCOUNTS.BILL;

CREATE TABLE ACCOUNTS.BILL (
	-- FORMAT FOR BILL_ID ORG_ID-YYYY-MM-DD-XXX(SEQUENCE)
	BILL_ID VARCHAR(128) NOT NULL,
	ORG_ID VARCHAR(128) NOT NULL,
	-- UTC TimeZone
	BILL_PERIOD_START TIMESTAMP NOT NULL,
	BILL_PERIOD_END TIMESTAMP NOT NULL,
	-- UTC TimeZone
	BILL_GENERATION_DATE_TIME TIMESTAMP NULL,
	-- ZoneId used for generating this Bill Report.
	-- Use this to convert the UTC time to corresponding Time Zone.
	-- Only for the PAY_BY_DATE_TIME field
	TIME_ZONE_ID VARCHAR(64) NOT NULL,
	-- Report saving field
	BILL_FILE_DATA BYTEA NOT NULL,
	-- UTC time
	CREATED_DATE_TIME TIMESTAMP NOT NULL,
	CREATED_BY_USER_ID VARCHAR(128) NOT NULL,
	CONSTRAINT BILL_PKEY PRIMARY KEY (BILL_ID)
);

ALTER TABLE ACCOUNTS.BILL ADD CONSTRAINT BILL_FKEY1 FOREIGN KEY (ORG_ID) REFERENCES TENANT.ORGANIZATION(ORG_ID);

CREATE SEQUENCE ACCOUNTS.BILL_NO_SEQUENCE START WITH 1001 INCREMENT BY 1 NO CYCLE;


