-- DROP SCHEMA DATA CASCADE;

CREATE SCHEMA DATA;

-- DROP TABLE DATA.USER;

CREATE TABLE DATA.USER (
	USER_ID VARCHAR(128) NOT NULL,
	USER_NAME VARCHAR(256) NOT NULL,
	USER_PASSWORD VARCHAR(16) NOT NULL,
	-- Additional Details and Comments
	USER_DETIALS VARCHAR(4096) NULL,
	CONSTRAINT USER_PKEY1 PRIMARY KEY (USER_ID)
);

-- DROP TABLE DATA.CONFIGURATION;

CREATE TABLE DATA.CONFIGURATION (
	USER_ID VARCHAR(128) NULL,
	key VARCHAR(2048) NOT NULL,
	value VARCHAR(4096) NULL,
	CONSTRAINT CONFIGURATION_PKEY PRIMARY KEY (key),
	CONSTRAINT USER_FKEY1 FOREIGN KEY (USER_ID) REFERENCES DATA.USER(USER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT
);

ALTER TABLE DATA.CONFIGURATION ALTER COLUMN value TYPE VARCHAR(65536);

-- DROP TABLE DATA.BASE_CONFIGURATION;

-- Holds only base product values
CREATE TABLE DATA.BASE_CONFIGURATION (
	key VARCHAR(2048) NOT NULL,
	value VARCHAR(4096) NULL,
	CONFIG_DETIALS VARCHAR(256) NULL,
	CONSTRAINT CONFIG_PKEY PRIMARY KEY (key)
);

ALTER TABLE DATA.BASE_CONFIGURATION ALTER COLUMN value TYPE VARCHAR(65536);

-- DROP TABLE DATA.FEATURE;

CREATE TABLE DATA.FEATURE (
	FEATURE_ID VARCHAR(128) NOT NULL,
	FEATURE_NAME VARCHAR(128) NOT NULL,
	FEATURE_DESCRIPTION VARCHAR(256) NULL,
	CONSTRAINT FEATURE_PKEY PRIMARY KEY (FEATURE_ID)
);

-- Applicable of Subscriptions at Org level only. Channel and User level cannot turn it off.
CREATE TABLE DATA.FEATURE_PACK_SUBSCRIPTION(
	SUBSCRIPTION_ID VARCHAR(128) NOT NULL,
	FEATURE_ID VARCHAR(128) NOT NULL,
	USER_ID VARCHAR(128) NOT NULL,
	-- Enforce of the contact. Y/N Values
	ENFORCE VARCHAR(1) NOT NULL,
	-- Stored in Z or UTC +00:00
	ENFORCE_START_DATE_TIME TIMESTAMP NOT NULL,
	ENFORCE_END_DATE_TIME TIMESTAMP NOT NULL,
	-- UTC time
	CREATED_DATE_TIME TIMESTAMP NOT NULL,
	CREATED_BY_USER_ID VARCHAR(128) NOT NULL,
	LAST_MODIFIED_DATE_TIME TIMESTAMP NOT NULL,
	LAST_MODIFIED_BY_USER_ID VARCHAR(128) NOT NULL,
	CONSTRAINT FEATURE_PACK_SUBSCRIPTION_PKEY PRIMARY KEY (SUBSCRIPTION_ID)
);

ALTER TABLE DATA.FEATURE_PACK_SUBSCRIPTION ADD CONSTRAINT FEATURE_PACK_SUBSCRIPTION_FKEY1 FOREIGN KEY (FEATURE_ID) REFERENCES DATA.FEATURE(FEATURE_ID);
ALTER TABLE DATA.FEATURE_PACK_SUBSCRIPTION ADD CONSTRAINT FEATURE_PACK_SUBSCRIPTION_FKEY2 FOREIGN KEY (USER_ID) REFERENCES DATA.USER(USER_ID);



-- DROP TABLE DATA.TRANSACTION;

CREATE TABLE DATA.TRANSACTION (
	USER_ID VARCHAR(128) NOT NULL,
	TRANSACTION_ID INT NOT NULL,
	-- Save what is received as is from the customer
	COLLABORATION_ID VARCHAR(128) NOT NULL,
	PROCESSED_BY_HOST_NAME VARCHAR(64) NOT NULL,
	PROCESSED_BY_HOST_IP VARCHAR(64) NOT NULL,
	LOAN_ID VARCHAR(64) NOT NULL,
	LOAN_TYPE VARCHAR(64) NOT NULL,
	-- BOTH/DU/LPA
	REQUEST_TYPE VARCHAR(16) NOT NULL,
	REQUEST_DATE_TIME TIMESTAMP NOT NULL,
	RESPONSE_DATE_TIME TIMESTAMP NOT NULL,
	API VARCHAR(16) NOT NULL,
	-- PROCESSING/SUCCESS/FAILURE
	STATUS VARCHAR(16) NOT NULL,
	CONSTRAINT TRANSACTION_PKEY PRIMARY KEY (TRANSACTION_ID)
);